version: 2

jobs:

 build:
   docker:
    - image: docker:19.03.5

   working_directory: ./

   steps:
    - checkout
    - setup_remote_docker

    - run:
       name: build client
       command: docker build -t cliet -f ./client/Dockerfile .

    - run:
       name: build server
       command: docker build -t server -f ./server/Dockerfile .

    - run:
       name: push frontend
       command: |
         docker login -u intelligentwater -p 1717intelligent-docker!
         docker push cliet:tag

    - run:
       name: push backend
       command: |
         docker login -u intelligentwater -p 1717intelligent-docker!
         docker push server:tag