version: 2.1

orbs:
  heroku: circleci/heroku@0.0.10

deploy: 
  docker: 
    - image: ircleci/node:10.16.3
  steps: 
    - checkout
    - run
      name: Deploy Main Main to Heroku
      commmand: |
        git push https://heroku:d5d8189d-826c-4111-aa1d-5f1cde57fc5a@git.heroku.com/intelligent-water.git main

workflows:
  version: 2
  build-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: main